/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ZStakeAware, ZStakeAwareInterface } from "../ZStakeAware";

const _abi = [
  {
    inputs: [],
    name: "wild",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ZStakeAware__factory {
  static readonly abi = _abi;
  static createInterface(): ZStakeAwareInterface {
    return new utils.Interface(_abi) as ZStakeAwareInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ZStakeAware {
    return new Contract(address, _abi, signerOrProvider) as ZStakeAware;
  }
}
